### ISSUE TITLE
CI : migrate jenkins pipeline to keyple-ops docker

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-ops#2]
Use the docker image in docker-ops

**Comment by odelcroi** [comment]
@brice-ruppen can you have a look at it?

**Comment by brice-ruppen** [comment]
I can but should it by writable by any user ?
If you need the Android SDK Platform 26 maybe we should install it on the Dockerfile.
It's a long process that should not be added to keyple builds.

**Comment by odelcroi** [comment]
I agree
